package com.ximena.todotask.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "tasks")
public class Task {
  /** Id */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** Titulo */
  @Column(name = "title", nullable = false, length = 100)
  private String title;

  /** Estado hecho o no hecho */
  @Column(name = "done", nullable = false)
  private Boolean done;

  /** Prioridad */
  @Column(name = "priority", nullable = false)
  private int priority;

  // With lombok, we can use @Data annotation to generate getters and setters automatically, so we don't need to write them manually.
  // constructors, getters, setters, and toString() method are generated by Lombok annotations.  
  
}
